service: posterfly

provider: 
  name: aws
  region: ap-south-1

resources:
  Resources:
    PosterflyUserTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: posterfly-auth
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: username-index
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: username
                KeyType: HASH