service: posterfly

provider: 
  name: aws
  region: ap-south-1

resources:
  Resources:
    PosterflyUserTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: posterfly-auth
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: provider
            AttributeType: S
          - AttributeName: providerId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: provider
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: providerId-provider-index
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: providerId
                KeyType: HASH
              - AttributeName: provider
                KeyType: RANGE
          - IndexName: username-index
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: username
                KeyType: HASH
          - IndexName: userId-index
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
